# Copyright 2025 JohnTheCoolingFan
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	lazy_static@1.4.0
	libc@0.2.82
"

inherit cargo

DESCRIPTION="A utility for mapping events from Linux event devices"
HOMEPAGE="https://github.com/KarsMulder/evsieve"

SRC_URI="
	https://github.com/KarsMulder/evsieve/archive/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="GPL-2+ MIT"
# Dependent crate licenses
LICENSE+=" || ( Apache-2.0 MIT )"
SLOT="0"
KEYWORDS="~amd64"
