name: Update a package

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Name of the package to update'
        required: true
        type: choice
        options:
          - rfmp
      version:
        description: 'Version of the package to generate, a github release tag'
        required: true
        type: string

jobs:
  generate_update:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/johnthecoolingfan/gentoo-action-image:main

    env:
      NEW_PACKAGE_EBUILD: "${{ inputs.package }}-${{ inputs.version }}.ebuild"

    defaults:
      run:
        shell: bash

    steps:
      - name: Install pycargoebuild
        run: emerge app-portage/pycargoebuild

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Checkout launcher repository
        uses: actions/checkout@v4
        with:
          repository: "JohnTheCoolingFan/${{ inputs.package }}"
          ref: ${{ inputs.version }}
          path: ${{ inputs.package }}

      - name: Create new ebuild file
        run: |
          cp $( find "repo/games-misc/${{ inputs.package }}" -regextype sed -regex ".*/${{ inputs.package}}-[0-9]\+\.[0-9]\+\.[0-9]\+\.ebuild" | sort | tail -n1 ) "repo/games-misc/${{ inputs.package }}/${NEW_PACKAGE_EBUILD}"

      - name: Run pycargoebuild
        run: pycargoebuild --inplace "repo/games-misc/${{ inputs.package }}/${NEW_PACKAGE_EBUILD}" "./${{ inputs.package }}/"

      - name: Run pkgcheck scan
        working-directory: ./repo/games-misc/${{ inputs.package }}
        run: pkgcheck scan

      - name: Install dependencies for building the package from ebuild
        run: emerge dev-lang/rust-bin

      - name: Build the package from ebuild
        run: ebuild "repo/games-misc/${{ inputs.package }}/${NEW_PACKAGE_EBUILD}" clean test install

      - name: Commit repository changes
        working-directory: ./repo
        run: |
          git add .
          pkgdev commit -m "games-misc/${{ inputs.package }}: add ${{ inputs.version }}"

      - name: Create a pull request with the new ebuild
        uses: peter-evans/create-pull-request@v6
        with:
          path: ./repo
          branch: ${{ inputs.package }}-${{ inputs.version }}
          title: "games-misc/${{ inputs.package }}: add ${{ inputs.version }}"
          body: "Automated update to games-misc/${{ inputs.package }}: new version [${{ inputs.version }}](https://github.com/JohnTheCoolingFan/${{ inputs.package }}/releases/tag/${{ inputs.version }})"
